services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: abcall-payment-local-api
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "5005:3005"
    env_file:
      - .env.local
    tty: true
    links:
      - db
    depends_on:
      - db
    networks:
      - payment_net
      - app_net
      
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - .env.db
    container_name: payment-local-db
    volumes:
      - "./data/postgresql:/var/lib/postgresql"
      - "./docker/postgresql:/docker-entrypoint-initdb.d"
    ports:
      - "5435:5432"
    networks:
      - payment_net




networks:
  payment_net:
    name: payment_net
    driver: bridge
  app_net:
    name: app_net
    driver: bridge